<?php

namespace AppBundle\Repository;

/**
 * AppBankAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppBankAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
