<?php

namespace AppBundle\Repository;

/**
 * AppBankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppBankRepository extends \Doctrine\ORM\EntityRepository
{
}
